# EduPlan AI - Qdrant Vector Database
services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-storage:/qdrant/storage  # Using named volume for FUSE compatibility
    environment:
      - QDRANT__STORAGE__WAL_CAPACITY_MB=32
      - QDRANT__STORAGE__WAL_SEGMENTS_AHEAD=0
    restart: unless-stopped
volumes:
  qdrant-storage:
    driver: local    
